# Generated by Django 3.2.3 on 2022-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0002_auto_20220506_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
