# Generated by Django 3.2.3 on 2022-05-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0003_expenditure_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'verbose_name': 'despesa', 'verbose_name_plural': 'despesas'},
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
