# Generated by Django 3.2.3 on 2022-05-13 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0004_auto_20220510_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='is_active',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes', verbose_name='Comprovante'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='scheduled',
            field=models.BooleanField(default=True, verbose_name='Agendado?'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
